<div class="jumbotron">
    <h1>Подтолкни себя к цели!</h1>
    <br>
    <object>
        <param name="movie" value="//www.youtube.com/v/T-D1KVIuvjA?version=3&amp;hl=ru_RU"/>
        <param name="allowFullScreen" value="true"/>
        <param name="allowscriptaccess" value="always"/>
        <embed src="//www.youtube.com/v/T-D1KVIuvjA?version=3&amp;hl=ru_RU" type="application/x-shockwave-flash" 
               width="560" height="315" allowscriptaccess="always" allowfullscreen="true" />
    </object>
    <br>
    <a class="btn btn-large btn-success" href="/register.html">Зарегистрируйтеcь уже сегодня!</a>
</div>

<hr>

<div class="row-fluid marketing">
    <div class="span6">
        <h4>Что такое цель?</h4>
        <p>Это мечта, имеющая точные сроки и другие измеряемые свойства.</p>

        <h4>Что такое мечта?</h4>
        <p>Это пока еще несостоявшаяся идея.</p>

        <h4>Как поставить цель?</h4>
        <p>Нужно невыполненную идею (мечту) ограничить временными рамками и определить для нее измеряемые свойства. Вот и все.</p>
    </div>

    <div class="span6">
        <h4>Как достигнуть цель?</h4>
        <p>Когда цель записана на бумаге, имеет временные ограничения, и наделена измеряемыми свойствами, ее реализация зависит только от НАШИХ действий.</p>

        <h4>Что мешает достигнуть цель?</h4>
        <p>Ответ очень простой. Недостаточная мотивация. Если цель не возбуждает, то и достигнуть ее будет очень сложно.</p>

        <h4>Почему цель не возбуждает?</h4>
        <p>Не та цель. Недостаточно важная цель. Нет веры, что цель можно достигнуть.</p>
    </div>
</div>

<hr>
