<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html lang="ru">
    <head>
        <title>Magic Pendel::Main</title>
        <meta charset="UTF-8">

        <meta name="description" content="">
        <meta name="keywords" content="Вставьте сюда Ваши эффективные ключевые слова" />
        <meta name="author" content="">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/bootstrap-responsive.min.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="/js/html5shiv/html5shiv-printshiv.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/wp-content/themes/clear-theme/img/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/wp-content/themes/clear-theme/img/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/wp-content/themes/clear-theme/img/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/wp-content/themes/clear-theme/img/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="/wp-content/themes/clear-theme/img/favicon.png">

        <style type="text/css">
            body {
                /*padding-top: 20px;*/
                padding-bottom: 40px;
            }

            /* Custom container */
            .container-narrow {
                margin: 0 auto;
                max-width: 700px;
            }
            .container-narrow > hr {
                /*margin: 30px 0;*/
            }

            /* Main marketing message and sign up button */
            .jumbotron {
                margin: 60px 0;
                text-align: center;
            }
            .jumbotron h1 {
                font-size: 4em;
                /*line-height: 1;*/
            }
            .jumbotron .btn {
                font-size: 21px;
                padding: 14px 24px;
            }

            /* Supporting marketing content */
            .marketing {
                margin: 60px 0;
            }
            .marketing p + h4 {
                margin-top: 28px;
            }

        </style>
    </head>
    <body>
        <div class="container-narrow">
            <!--header-->
            <div class="masthead">
                <h3 class="muted"><img src="img/logo.png" alt="Magic Pendel"/></h3>
                <ul class="nav nav-pills pull-right">
                    <li <?php if( $this->paramsView()->getAction() == 'index') echo 'class="active"'; ?> ><a href="/">Главная</a></li>
                    <li <?php if( $this->paramsView()->getAction() == 'about') echo 'class="active"'; ?> ><a href="/about">О проекте</a></li>
                    <li><a href="#">Контакты</a></li>
                    <!--<li><a href="#">Купить пендель</a></li>-->
                    <!--<li><a href="#">Личный кабинет</a></li>-->
                </ul>
            </div>

            <hr>
            <!--/header-->
            <?php echo $this->content; ?>

            <div class="footer">
                <p>All rights reserved © MaxML, 2013</p>
            </div>

        </div> <!-- /container -->


        <!--Javascript-->
        <script src="js/jquery/jquery.js"></script>
        <script src="js/twitter-bootstrap/js/bootstrap.js"></script>

    </body>
</html>
